### ISSUE TITLE
Http.php升级后报错了

### ISSUE THREAD

**Issue by linjuchen** [Hanson/foundation-sdk#14]
public function __construct(Foundation $app)
    {
        $this->app = $app;
    }
=======================================
我以前正常的程序，现在需要把这个屏蔽掉才能正常工作。
这个app 有什么约定吗？

**Comment by Hanson** [comment]
报什么错？

**Comment by qbhy** [comment]
@linjuchen 加 QQ 群帮你解决，570769430

**Comment by qbhy** [comment]
不要自己 new Http 就好了，继承 Foundation 后自带一个 $this->http 模块了，或者你要自己new的话，你得把你自己的 Foundation 实例传进去，又或者你重写一下 Http 的构造方法

**Comment by Hanson** [comment]
@qbhy 把构造函数改为 可为 null 吧

**Comment by qbhy** [comment]
@Hanson 不行，要从 $app 获取 guzzle_hanlder 配置，强行兼容不太好

**Comment by qbhy** [comment]
这就是版本要发3.1 ，而不是 3.0.1 的原因了

**Comment by qbhy** [comment]
没有其他问题的关闭问题吧

**Comment by bolechen** [comment]
其它依赖包用 ^3.0 的话会报错哦，建议改成大版本？ @qbhy 

@see https://github.com/Hanson/youzan-sdk/issues/20

**Comment by qbhy** [comment]
@Hanson 大版本

**Comment by Hanson** [comment]
那我改个大版本吧 @bolechen @qbhy @linjuchen

**Comment by bolechen** [comment]
`hanson/youzan-sdk` 升级到 4.0 的依赖后报以下错误，是否跟这个 PR 有关？ @qbhy @Hanson 

```
production.ERROR: Trying to get property 'http' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'http' of non-object at /xxx/foundation-sdk/src/AbstractAccessToken.php:221)
```
