### ISSUE TITLE
request 无法获取服务端返回的数据

### ISSUE THREAD

**Issue by duckjiangwei** [Hanson/foundation-sdk#29]
类 Hanson\Foundation\Http 的 request 方法，在里面调用了 $response->getBody() 记录日志，然后再返回 $response，使用 $response->getBody()->getContents() 获取返回的内容，是个空字符串。

是否需要加个 $response->getBody()->rewind() 将指针重置到起始位置。

**Comment by cys138138** [comment]
您好，你的邮件我已收到！
