### ISSUE TITLE
这么好的东西能不能出个使用文档呀？手册也行呀，拜托拜托

### ISSUE THREAD

**Issue by cys138138** [Hanson/foundation-sdk#3]

**Comment by Hanson** [comment]
可以尝试看看这个 https://laravel-china.org/articles/15038/sdk-development-advanced-edition-uncover-the-mysterious-veil-of-foundation-sdk

**Comment by bolechen** [comment]
+1，上面的链接找了半天，建议补充到 readme 中吧

**Comment by Hanson** [comment]
@bolechen 好的，我加到 readme上面
